from .. import ENV as _ENV
from dev import DEV_HOT_NEWS_PATH, DEV_FULL_NEWS_PATH, DEV_TOP_MONGO_ARGS, DEV_HOT_MONGO_ARGS
from debug import DEBUG_HOT_NEWS_PATH, DEBUG_FULL_NEWS_PATH, DEBUG_TOP_MONGO_ARGS, DEBUG_TOP_MONGO_ARGS

if _ENV:
    HOT_NEWS_PATH = DEV_HOT_NEWS_PATH
    FULL_NEWS_PATH = DEV_FULL_NEWS_PATH

    TOP_MONGO_ARGS = DEV_TOP_MONGO_ARGS
    HOT_MONGO_ARGS = DEV_HOT_MONGO_ARGS
else:
    HOT_NEWS_PATH = DEBUG_HOT_NEWS_PATH
    FULL_NEWS_PATH = DEBUG_FULL_NEWS_PATH

    TOP_MONGO_ARGS = DEBUG_TOP_MONGO_ARGS
    HOT_MONGO_ARGS = DEBUG_TOP_MONGO_ARGS



