DEV_FULL_NEWS_PATH = '/data/news/csf_news/'
DEV_HOT_NEWS_PATH = '/data/news/csf_hot_news/'

DEV_MONGO_HOST = '10.0.3.10'
DEV_MONGO_PORT = 27017
DEV_MONGO_DB = 'news'
DEV_MONGO_TOP_TBALE = 'topnews_analyse'
DEV_MONGO_HOT_TBALE = 'hotnews_analyse'

DEV_TOP_MONGO_ARGS = (DEV_MONGO_HOST, DEV_MONGO_PORT, DEV_MONGO_DB, DEV_MONGO_TOP_TBALE)
DEV_HOT_MONGO_ARGS = (DEV_MONGO_HOST, DEV_MONGO_PORT, DEV_MONGO_DB, DEV_MONGO_HOT_TBALE)

